apiVersion: v1
kind: Service
metadata:
  name: churn-api-service
spec:
  type: LoadBalancer # IP Externo
  selector:
    app: churn-api
  ports:
  - protocol: TCP
    port: 80       # Porta WEB
    targetPort: 8000 # Porta da API